/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/cloud/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Cloud1({sceneOpacity, ...props}) {
  const { nodes, materials } = useGLTF('./models/cloud1/model.glb')

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}> 
        <meshStandardMaterial 
            // {...materials['lambert2sg.001']} 
            ref={materialRef}
            envMapIntensity={2} //math the coluds more impacted by the environment colors
            transparent />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/cloud1/model.glb')
